### ISSUE TITLE
API Documentation Process

### ISSUE THREAD

**Issue by CharlesLiuyx** [tensorspace-team/tensorspace#76]
Complete the API docs

## Model
- [x] TSP.model.Sequential [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Sequential_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Sequential)
- [x] TSP.model.Model [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Model_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Model)

## Layer
- [x] Conv2d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Conv2d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Conv2d) ![#FFFF2E](https://placehold.it/15/FFFF2E/000000?text=+) 
- [x] Conv1d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Conv1d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Conv1d)
- [x] Input1d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Input1d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Input1d)
- [x] Input2d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Input2d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Input2d) ![#EEEEEE](https://placehold.it/15/EEEEEE/000000?text=+)
- [x] Input3d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Input3d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Input3d)
- [x] Padding2d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_padding2d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_padding2d) ![#6eb6ff](https://placehold.it/15/6eb6ff/000000?text=+)
- [x] Padding1d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_padding1d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_padding1d)
- [x] Pooling2d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Pooling2d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Pooling2d) ![#00ffff](https://placehold.it/15/00ffff/000000?text=+) 
- [x] Pooling1d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Pooling1d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Pooling1d)
- [x] Dense [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Dense_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Dense) ![#00ff00](https://placehold.it/15/00ff00/000000?text=+)
- [x] Output1d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Output1d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Output1d) ![#EEEEEE](https://placehold.it/15/EEEEEE/000000?text=+) 
- [x] UpSampling2d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_UpSampling2d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_UpSampling2d) ![#30e3ca](https://placehold.it/15/30e3ca/000000?text=+)
- [x] UpSampling1d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_UpSampling1d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_UpSampling1d)
- [x] Reshape [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Reshape_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Reshape) ![#a287f4](https://placehold.it/15/a287f4/000000?text=+)
Reshape1d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Reshape1d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Reshape1d)
Reshape2d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Reshape2d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Reshape2d)
- [x] Flatten [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Flatten_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Flatten) ![#dfe2fe](https://placehold.it/15/dfe2fe/000000?text=+)
- [x] Cropping2d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Cropping2d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Cropping2d) ![#cefc86](https://placehold.it/15/cefc86/000000?text=+)
- [x] Cropping1d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Cropping1d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Cropping1d)
- [x] Conv2dTranspose [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Conv2dTranspose_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Conv2dTranspose) ![#ff5722](https://placehold.it/15/ff5722/000000?text=+)
- [x] YoloGrid [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_YoloGrid_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_YoloGrid)
- [x] OutputDetection [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_OutputDetection_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_OutputDetection)
- [x] GlobalPooling2d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_GlobalPooling2d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_GlobalPooling2d)  ![#0074e4](https://placehold.it/15/0074e4/000000?text=+)
- [x] GlobalPooling1d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_GlobalPooling1d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_GlobalPooling1d)
- [x] Layer2d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Layer2d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Layer2d) ![#f08a5d](https://placehold.it/15/f08a5d/000000?text=+)
- [x] Layer1d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Layer1d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Layer1d)
- [x] Layer3d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Layer3d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Layer3d)
- [x] Activation2d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Activation2d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Activation2d) ![#fc5c9c](https://placehold.it/15/fc5c9c/000000?text=+)
- [x] Activation1d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Activation1d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Activation1d)
- [x] Activation3d [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Activation3d_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Activation3d)

## Merge

- [x]  Add [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Merge_Add_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Merge_Add)  ![#e23e57](https://placehold.it/15/e23e57/000000?text=+) 
- [x]  Average [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Merge_Average_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Merge_Average)  ![#e23e57](https://placehold.it/15/e23e57/000000?text=+)
- [x]  Dot [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Merge_Dot_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Merge_Dot)  ![#e23e57](https://placehold.it/15/e23e57/000000?text=+)
- [x]  Maximum [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Merge_Maximum_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Merge_Maximum)  ![#e23e57](https://placehold.it/15/e23e57/000000?text=+)
- [x]  Multiply [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Merge_Multiply_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Merge_Multiply)  ![#e23e57](https://placehold.it/15/e23e57/000000?text=+)
- [x]  Substract [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Merge_Substract_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Merge_Substract)  ![#e23e57](https://placehold.it/15/e23e57/000000?text=+)
- [x]  Concatenate [zh](https://github.com/syt123450/tensorspace/wiki/API_Docs_Merge_Concatenate_zh) | [en](https://github.com/syt123450/tensorspace/wiki/API_Docs_Merge_Concatenate)  ![#f9a1bc](https://placehold.it/15/f9a1bc/000000?text=+)
